<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-6ORDNF9" failures="1" tests="4" name="Test" time="117.789" errors="0" timestamp="2023-01-13T10:12:47 IST">
  <testcase classname="testNg_TestCases.CreateContactTest" name="createContact" time="3.573">
    <skipped/>
  </testcase> <!-- createContact -->
  <testcase classname="testNg_TestCases.CreateContactTest" name="createContact" time="2.941">
    <skipped/>
  </testcase> <!-- createContact -->
  <testcase classname="testNg_TestCases.CreateContactTest" name="createContact" time="2.967">
    <skipped/>
  </testcase> <!-- createContact -->
  <testcase classname="testNg_TestCases.CreateContactTest" name="createContact" time="3.275">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	null">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
null
at testNg_TestCases.CreateContactTest.createContact(CreateContactTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- createContact -->
  <testcase classname="testNg_TestCases.CreateContactTest" name="createOrgRecycleBin" time="0.0">
    <ignored/>
  </testcase> <!-- createOrgRecycleBin -->
</testsuite> <!-- Test -->
